# Generated by Django 2.1.5 on 2019-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='seen_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
