# Generated by Django 2.2.4 on 2019-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aducation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دانش آموز'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'کارشناسی ارشد'), (6, 'دکترا')]),
        ),
    ]
