# Generated by Django 2.2.4 on 2019-08-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_auto_20190810_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aducation',
            new_name='education',
        ),
    ]
