# Generated by Django 2.2.4 on 2019-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_auto_20190810_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دانش آموز'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'کارشناسی ارشد'), (6, 'دکترا')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
