# Generated by Django 2.1.5 on 2019-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0005_registeredcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='_education',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'تعیین شنده'), (1, 'دانش آموز'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'کارشناسی ارشد'), (6, 'دکترا')], null=True),
        ),
    ]
