# Generated by Django 2.2.4 on 2019-08-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='course_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.SessionCourse'),
        ),
    ]
