# Generated by Django 2.2.4 on 2019-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_sessionexercise_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentsfiles',
            name='file',
            field=models.FileField(upload_to='attach_file/%y-%m-%d_%H:%M'),
        ),
    ]
