# Generated by Django 2.1.5 on 2019-08-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_base', '0004_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attach-files/%y-%m-%d_%H:%M')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('aparat_video', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('course_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.CourseSession')),
            ],
        ),
        migrations.RemoveField(
            model_name='attachmentsfiles',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sessioncourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sessionexercise',
            name='course_session',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AttachmentsFiles',
        ),
        migrations.DeleteModel(
            name='SessionCourse',
        ),
        migrations.DeleteModel(
            name='SessionExercise',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Course'),
        ),
    ]
