# Generated by Django 2.1.5 on 2019-09-03 20:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_auto_20190830_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesessionexercise',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
